// components/SearchModal.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";

interface Suggestion {
  did: string;
  handle: string;
  displayName: string | null;
  avatar: string | null;
}

function SearchIcon({ className = "h-5 w-5" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      className={className}
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

export function SearchModal() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [suggestions, setSuggestions] = useState<Suggestion[]>([]);
  const [loading, setLoading] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const normalizedQuery = useMemo(() => query.trim(), [query]);

  // Open with Cmd/Ctrl+K
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        setOpen(true);
      }
    }
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, []);

  // Auto-focus input when modal opens
  useEffect(() => {
    if (open) {
      // rAF ensures the modal is rendered before we focus
      requestAnimationFrame(() => inputRef.current?.focus());
    }
  }, [open]);

  // Fetch search results
  useEffect(() => {
    if (!normalizedQuery) {
      setSuggestions([]);
      return;
    }

    const controller = new AbortController();
    const APPVIEW = "https://public.api.bsky.app";
    const timeout = setTimeout(async () => {
      setLoading(true);
      try {
        const response = await fetch(
          `${APPVIEW}/xrpc/app.bsky.actor.searchActors?q=${encodeURIComponent(normalizedQuery)}&limit=8`,
          { signal: controller.signal },
        );
        if (!response.ok) return;
        const data = (await response.json()) as {
          actors?: {
            did: string;
            handle: string;
            displayName?: string;
            avatar?: string;
          }[];
        };
        setSuggestions(
          (data.actors ?? []).map((a) => ({
            did: a.did,
            handle: a.handle,
            displayName: a.displayName ?? null,
            avatar: a.avatar ?? null,
          })),
        );
      } catch {
        setSuggestions([]);
      } finally {
        setLoading(false);
      }
    }, 120);

    return () => {
      clearTimeout(timeout);
      controller.abort();
    };
  }, [normalizedQuery]);

  function closeModal() {
    setOpen(false);
    setQuery("");
    setSuggestions([]);
  }

  function openHandle(handle: string) {
    closeModal();
    window.location.href = `/profile/${handle}`;
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        aria-label="Search handles (Ctrl+K)"
        className="flex h-10 items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 text-[var(--muted)] outline-none transition-colors hover:border-[var(--accent)] hover:text-[var(--text)]"
      >
        <SearchIcon className="h-4 w-4 shrink-0" />
        <span className="hidden text-sm sm:inline">Search…</span>
        <kbd className="hidden items-center gap-0.5 rounded border border-[var(--border)] px-1.5 py-0.5 font-mono text-[10px] leading-none lg:inline-flex">
          <span className="text-xs">⌘</span>K
        </kbd>
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-start justify-center bg-black/50 pt-[15vh] backdrop-blur-sm"
          onClick={(e) => {
            if (e.target === e.currentTarget) closeModal();
          }}
          role="dialog"
          aria-modal="true"
          aria-label="Search"
        >
          <div className="mx-4 w-full max-w-lg overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)] shadow-2xl">
            <div className="flex items-center gap-3 border-b border-[var(--border)] px-4 py-3">
              <SearchIcon />
              <input
                ref={inputRef}
                value={query}
                onChange={(e) => setQuery(e.target.value.replace(/^@/, ""))}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && normalizedQuery) {
                    openHandle(normalizedQuery);
                  }
                  if (e.key === "Escape") closeModal();
                }}
                placeholder="Search handle…"
                className="flex-1 bg-transparent text-base text-[var(--text)] placeholder-[var(--muted)] outline-none"
              />
              <kbd className="inline-flex h-6 items-center rounded border border-[var(--border)] px-1.5 font-mono text-xs text-[var(--muted)]">
                esc
              </kbd>
            </div>

            {(loading || suggestions.length > 0 || normalizedQuery) && (
              <div className="max-h-72 overflow-auto p-2">
                {loading ? (
                  <p className="px-3 py-2 text-sm text-[var(--muted)]">
                    Searching…
                  </p>
                ) : suggestions.length === 0 ? (
                  <p className="px-3 py-2 text-sm text-[var(--muted)]">
                    No results for &ldquo;{normalizedQuery}&rdquo;
                  </p>
                ) : (
                  <ul>
                    {suggestions.map((suggestion) => (
                      <li key={suggestion.did}>
                        <button
                          type="button"
                          onClick={() => openHandle(suggestion.handle)}
                          className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left hover:bg-[var(--surface-strong)]"
                        >
                          {suggestion.avatar ? (
                            <img
                              src={suggestion.avatar}
                              alt=""
                              loading="lazy"
                              width={36}
                              height={36}
                              className="size-9 shrink-0 rounded-full object-cover"
                            />
                          ) : (
                            <span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-[var(--surface-strong)] text-sm font-semibold text-[var(--text)]">
                              {(suggestion.displayName ?? suggestion.handle)
                                .charAt(0)
                                .toUpperCase()}
                            </span>
                          )}
                          <span className="flex min-w-0 flex-col">
                            <span className="truncate text-sm font-medium text-[var(--text)]">
                              {suggestion.displayName ?? suggestion.handle}
                            </span>
                            <span className="truncate text-xs text-[var(--muted)]">
                              @{suggestion.handle}
                            </span>
                          </span>
                        </button>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}

// components/SearchModal.vue
<script setup lang="ts">
interface Suggestion {
  did: string;
  handle: string;
  displayName: string | null;
  avatar: string | null;
}

const open = ref(false);
const query = ref('');
const suggestions = ref<Suggestion[]>([]);
const loading = ref(false);
const inputRef = ref<HTMLInputElement | null>(null);
const normalizedQuery = computed(() => query.value.trim());

onMounted(() => {
  document.addEventListener('keydown', (e: KeyboardEvent) => {
    if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
      e.preventDefault();
      open.value = true;
    }
  });
});

watch(open, (val) => {
  if (val) requestAnimationFrame(() => inputRef.value?.focus());
});

let searchTimeout: ReturnType<typeof setTimeout> | undefined;
let controller: AbortController | undefined;

watch(normalizedQuery, (q) => {
  clearTimeout(searchTimeout);
  controller?.abort();
  if (!q) { suggestions.value = []; return; }
  controller = new AbortController();
  searchTimeout = setTimeout(async () => {
    loading.value = true;
    try {
      const r = await fetch(`https://public.api.bsky.app/xrpc/app.bsky.actor.searchActors?q=${encodeURIComponent(q)}&limit=8`, { signal: controller!.signal });
      if (!r.ok) return;
      const data = await r.json() as { actors?: { did: string; handle: string; displayName?: string; avatar?: string }[] };
      suggestions.value = (data.actors ?? []).map(a => ({ did: a.did, handle: a.handle, displayName: a.displayName ?? null, avatar: a.avatar ?? null }));
    } catch { suggestions.value = []; }
    finally { loading.value = false; }
  }, 120);
});

function closeModal() {
  open.value = false;
  query.value = '';
  suggestions.value = [];
}

function openHandle(handle: string) {
  closeModal();
  window.location.href = `/profile/${handle}`;
}
</script>

<template>
  <button
    type="button"
    @click="open = true"
    aria-label="Search handles (Ctrl+K)"
    class="flex h-10 items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 text-[var(--muted)] outline-none transition-colors hover:border-[var(--accent)] hover:text-[var(--text)]"
  >
    <svg viewBox="0 0 24 24" class="h-4 w-4 shrink-0" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="8" /><path d="m21 21-4.3-4.3" /></svg>
    <span class="hidden text-sm sm:inline">Search…</span>
    <kbd class="hidden items-center gap-0.5 rounded border border-[var(--border)] px-1.5 py-0.5 font-mono text-[10px] leading-none lg:inline-flex"><span class="text-xs">⌘</span>K</kbd>
  </button>

  <Teleport to="body">
    <div
      v-if="open"
      class="fixed inset-0 z-50 flex items-start justify-center bg-black/50 pt-[15vh] backdrop-blur-sm"
      @click.self="closeModal"
      role="dialog"
      aria-modal="true"
      aria-label="Search"
    >
      <div class="mx-4 w-full max-w-lg overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)] shadow-2xl">
        <div class="flex items-center gap-3 border-b border-[var(--border)] px-4 py-3">
          <svg viewBox="0 0 24 24" class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="8" /><path d="m21 21-4.3-4.3" /></svg>
          <input
            ref="inputRef"
            v-model="query"
            @keydown.enter="normalizedQuery && openHandle(normalizedQuery)"
            @keydown.escape="closeModal"
            placeholder="Search handle…"
            class="flex-1 bg-transparent text-base text-[var(--text)] placeholder-[var(--muted)] outline-none"
          />
          <kbd class="inline-flex h-6 items-center rounded border border-[var(--border)] px-1.5 font-mono text-xs text-[var(--muted)]">esc</kbd>
        </div>

        <div v-if="loading || suggestions.length > 0 || normalizedQuery" class="max-h-72 overflow-auto p-2">
          <p v-if="loading" class="px-3 py-2 text-sm text-[var(--muted)]">Searching…</p>
          <p v-else-if="suggestions.length === 0" class="px-3 py-2 text-sm text-[var(--muted)]">No results for "{{ normalizedQuery }}"</p>
          <ul v-else>
            <li v-for="s in suggestions" :key="s.did">
              <button type="button" @click="openHandle(s.handle)" class="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left hover:bg-[var(--surface-strong)]">
                <img v-if="s.avatar" :src="s.avatar" alt="" loading="lazy" width="36" height="36" class="size-9 shrink-0 rounded-full object-cover" />
                <span v-else class="flex size-9 shrink-0 items-center justify-center rounded-full bg-[var(--surface-strong)] text-sm font-semibold text-[var(--text)]">{{ (s.displayName ?? s.handle).charAt(0).toUpperCase() }}</span>
                <span class="flex min-w-0 flex-col">
                  <span class="truncate text-sm font-medium text-[var(--text)]">{{ s.displayName ?? s.handle }}</span>
                  <span class="truncate text-xs text-[var(--muted)]">@{{ s.handle }}</span>
                </span>
              </button>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </Teleport>
</template>
