// app/profile/[handle]/page.tsx
import type { Metadata } from "next";
import { Suspense } from "react";
import { getActorProfile } from "@/lib/atproto/profiles";
import { getProfileRecordsFromPds } from "@/lib/atproto/records";
import { ProfileDisplay } from "@/components/ProfileDisplay";
import { FollowsSection, FollowsSkeleton } from "@/components/FollowsSection";
import { FloatingProfileBack } from "@/components/FloatingProfileBack";

// Regenerate at most once per hour; revalidateTag(profileRecordsTag) in
// /api/status immediately busts this page when the owner saves their profile.
export const revalidate = 3600;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ handle: string }>;
}): Promise<Metadata> {
  const handle = decodeURIComponent((await params).handle).replace(/^@/, "");
  return {
    title: `@${handle} – pronouns.blue`,
    description: `View @${handle}'s preferred names and pronouns on pronouns.blue`,
  };
}

export default async function HandleProfilePage({
  params,
}: {
  params: Promise<{ handle: string }>;
}) {
  const handle = decodeURIComponent((await params).handle).replace(/^@/, "");

  const actor = await getActorProfile(handle);

  if (!actor) {
    return (
      <main className="mx-auto flex w-full max-w-3xl flex-1 flex-col items-center justify-center px-4 pt-24 pb-16 text-center">
        <h1 className="text-2xl font-bold text-[var(--text)]">
          Profile not found
        </h1>
        <p className="mt-2 text-[var(--muted)]">
          This user doesn&apos;t exist or hasn&apos;t signed in yet.
        </p>
      </main>
    );
  }

  const profile = await getProfileRecordsFromPds(actor.did);
  const title = actor.displayName ?? actor.handle;

  return (
    <>
      <ProfileDisplay
        title={title}
        handle={actor.handle}
        avatar={actor.avatar}
        groups={profile.groups}
        bskyFallbackPronouns={actor.pronouns}
        profileDid={actor.did}
      />
      <Suspense fallback={<FollowsSkeleton />}>
        <FollowsSection did={actor.did} title={title} />
      </Suspense>
      <FloatingProfileBack title={title} avatar={actor.avatar} />
    </>
  );
}

// pages/profile/[handle].vue
<script setup lang="ts">
import { setResponseHeader } from "h3";
import { getActorProfile } from "~/lib/atproto/profiles";
import { getProfileRecordsFromPds } from "~/lib/atproto/records";

const route = useRoute();
const handle = decodeURIComponent(String(route.params.handle ?? "")).replace(
  /^@/,
  "",
);

const { data, error } = await useAsyncData(`profile-${handle}`, async () => {
  const actor = await getActorProfile(handle);
  if (!actor) return null;

  const profile = await getProfileRecordsFromPds(actor.did);

  const followsRes = (await fetch(
    `https://public.api.bsky.app/xrpc/app.bsky.graph.getFollows?actor=${encodeURIComponent(actor.did)}&limit=48`,
  ).then((r) => (r.ok ? r.json() : { follows: [], cursor: undefined }))) as {
    follows: {
      did: string;
      handle: string;
      displayName?: string;
      avatar?: string;
    }[];
    cursor?: string;
  };

  return {
    actor,
    groups: profile.groups,
    initialFollows: followsRes.follows.map((f) => ({
      did: f.did,
      handle: f.handle,
      displayName: f.displayName ?? null,
      avatar: f.avatar ?? null,
    })),
    initialCursor: followsRes.cursor,
  };
});

// 404 if actor not found
if (!data.value || error.value) {
  throw createError({ statusCode: 404, statusMessage: "Profile not found" });
}

const { actor, groups, initialFollows, initialCursor } = data.value;

// Set CDN cache headers
const event = useRequestEvent();
if (event) {
  setResponseHeader(
    event,
    "Cache-Control",
    "public, s-maxage=3600, stale-while-revalidate=86400",
  );
}

useHead({
  title: `@${actor.handle} – pronouns.blue`,
  meta: [
    {
      name: "description",
      content: `View @${actor.handle}'s preferred names and pronouns on pronouns.blue`,
    },
    { property: "og:title", content: `@${actor.handle} – pronouns.blue` },
    {
      property: "og:description",
      content: `View @${actor.handle}'s preferred names and pronouns on pronouns.blue`,
    },
    { property: "og:image", content: `/og/profile/${actor.handle}.png` },
  ],
});

const title = actor.displayName ?? actor.handle;
</script>

<template>
  <div>
    <ProfileDisplay
      :title="title"
      :handle="actor.handle"
      :avatar="actor.avatar ?? null"
      :groups="groups"
      :bsky-fallback-pronouns="actor.pronouns"
      :profile-did="actor.did"
    />

    <section
      v-if="initialFollows.length > 0"
      class="mx-auto w-full max-w-3xl px-4 pb-16 sm:px-6"
    >
      <div class="border-t border-[var(--border)] pt-10">
        <h2 class="mb-1 text-lg font-semibold text-[var(--text)]">
          More to explore
        </h2>
        <p class="mb-6 text-sm text-[var(--muted)]">
          People {{ title }} follows on Bluesky
        </p>
        <FollowsGrid
          :initial-follows="initialFollows"
          :initial-cursor="initialCursor"
          :did="actor.did"
        />
      </div>
    </section>

    <FloatingProfileBack :title="title" :avatar="actor.avatar ?? null" />
  </div>
</template>
